Organizations:
  - &MogadishuUniversity
    Name: MogadishuUniversityMSP
    ID: MogadishuUniversityMSP
    MSPDir: ../organizations/peerOrganizations/mogadishu.university.so/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('MogadishuUniversityMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('MogadishuUniversityMSP.admin')"
      Admins:
        Type: Signature
        Rule: "OR('MogadishuUniversityMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('MogadishuUniversityMSP.member')"
    AnchorPeers:
      - Host: peer0.mogadishu.university.so
        Port: 7051

  - &HargeisaUniversity
    Name: HargeisaUniversityMSP
    ID: HargeisaUniversityMSP
    MSPDir: ../organizations/peerOrganizations/hargeisa.university.so/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('HargeisaUniversityMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('HargeisaUniversityMSP.admin')"
      Admins:
        Type: Signature
        Rule: "OR('HargeisaUniversityMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('HargeisaUniversityMSP.member')"
    AnchorPeers:
      - Host: peer0.hargeisa.university.so
        Port: 8051

  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/ministry.gov.so/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_5: true
  Orderer: &OrdererCapabilities
    V2_5: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.ndts.gov.so:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  EtcdRaft:
    Consenters:
      - Host: orderer.ndts.gov.so
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/ministry.gov.so/orderers/orderer.ministry.gov.so/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/ministry.gov.so/orderers/orderer.ministry.gov.so/tls/server.crt
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  EducationOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *MogadishuUniversity
          - *HargeisaUniversity
  
  EducationChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *MogadishuUniversity
        - *HargeisaUniversity
