OrdererOrgs:
  - Name: Orderer
    Domain: ministry.gov.so
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: MogadishuUniversity
    Domain: mogadishu.university.so
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: HargeisaUniversity
    Domain: hargeisa.university.so
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

